[tool.black]
line-length=80
skip-string-normalization=true
skip-magic-trailing-comma=true

[tool.isort]
profile = "black"
known_first_party="octodns_constellix"
known_octodns="octodns"
line_length=80
sections="FUTURE,STDLIB,THIRDPARTY,OCTODNS,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
filterwarnings = [
    'error',
    # pycountry_mappings -> repoze.lru ->
    'ignore:pkg_resources is deprecated',
    'ignore:Deprecated call to `pkg_resources.declare_namespace',
]
pythonpath = "."
